quantities = {
    # Base Quantities
    'Time':'',
    'Distance':'',
    'Mass':'',
    'Current':'',
    'Tempurature':'',
    'Amount':'',
    'LuminousIntensity':'',

    # Disambiguations
    'Length':'Distance',
    'Radius':'Distance',
    'Heat':'Energy',

    # Quantities with named units in SI system
    'Frequency':'Time^-1',
    'Angle':'Length / Radius',
    'SolidAngle':'Area / Radius^2',
    'Force':'Mass Acceleration',
    'Pressure':'Force / Area',
    'Energy':'Force Distance',
    'Power':'Energy / Time',
    'Charge':'Current Time',
    'Voltage':'Power / Current',
    'Capacitance':'Charge / Voltage',
    'Resistance':'Voltage / Current',
    'Reactance':'Resistance i',
    'Impedance':'Resistance + Reactance',
    'Conductance':'Current / Voltage',
    'MagneticFlux':'Voltage Time',
    'MagneticFluxDensity':'MagneticFlux / Area',
    'Inductance':'MagneticFlux / Current',
    'LuminousFlux':'LuminousIntensity / SolidAngle',
    'Illuminance':'LuminousFlux / Area',
    'Activity':'Time^-1',
    'AbsorbedRadiationDose':'Energy / Mass',
    'EquivalentRadiationDose':'Energy / Mass',
    'CatalyticActivity':'Amount / Time',

    # Kinematics
    'Velocity':'Distance / Time',
    'Acceleration':'Velocity / Time',
    'Jerk':'Acceleration / Time',
    'Snap':'Jerk / Time',
    'Yank':'Mass Jerk',
    'AngularVelocity':'Angle / Time',
    'AngularAcceleration':'AngularVelocity / Time',
    'FrequencyDrift':'Frequency / Time',
    'VolumetricFlow':'Volume / Time',

    # Mechanics
    'Area':'Length^2',
    'Volume':'Length Area',
    'Momentum':'Force Time',
    'AngularMomentum':'Momentum Radius',
    'Torque':'Force Radius',
    'SpatialFrequency':'Length^-1',
    'OpticalPower':'Distance^-1',
    'Curvature':'Radius^-1',
    'AreaDensity':'Mass / Area',
    'Density':'Mass / Volume',
    'SpecificVolume':'Volume / Mass',
    'Action':'Energy Time',
    'SpecificEnergy':'Energy / Mass',
    'EnergyDensity':'Energy / Volume',
    'SurfaceTension':'Force / Distance',
    'Stiffness':'Energy / Area',
    'Diffusivity':'Area / Time',
    'KinematicViscosity':'DynamicViscosity / Density',
    'DynamicViscosity':'Pressure Time',
    'LinearMassDensity':'Mass / Length',
    'MassFlowRate':'Mass / Time',
    'AbsorbedRadiationDoseRate':'AbsorbedRadiationDose / Time',
    'FuelEfficiency':'Distance / Volume',
    'PowerDensity':'Power / Volume',
    'EnergyFluxDensity':'Power / Area',
    'Compressibility':'Pressure^-1',
    'InertialMoment':'Mass Radius^2',
    'SpecificAngularMomentum':'AngularMomentum / Mass',
    
    # Radiometry
    'RadiantFlux':'Heat / Time',
    'SpectralPower':'RadiantFlux / Length',
    'SpectralFlux':'RadiantFlux / Length',
    'RadiantIntensity':'RadiantFlux / SolidAngle',
    'SpectralIntensity':'RadiantIntensity / Length',
    'Radiance':'RadiantIntensity / Area',
    'SpectralRadiance':'Radiance / Length',
    'Irradiance':'RadiantFlux / Area',
    'SpectralIrradiance':'Irradiance / Length',
    'Radiosity':'RadiantFlux / Area',
    'SpectralRadiosity':'Radiosity / Length',
    'RadiantExitance':'RadiantFlux / Area',
    'SpectralExitance':'RadiantExitance / Length',
    'RadiantExposure':'Irradiance Time',
    'SpectralExposure':'RadiantExposure / Length',

    # Photometry
    'LuminousEnergy':'LuminousFlux Time',
    'Luminance':'LuminousIntensity / Area',
    'LuminousExitance':'LuminousFlux / Area',
    'LuminousExposure':'LuminousExitance Time',
    'LuminousEnergyDensity':'LuminousEnergy / Volume',
    'RadiationEfficacy':'LuminousFlux / RadiantFlux',
    'LuminousEfficacy':'LuminousFlux / Power',

    # Chemistry
    'Molarity':'Amount / Volume',
    'MolarVolume':'Volume / Amount',
    'MolarHeatCapacity':'HeatCapacity / Amount',
    'MolarEnergy':'Energy / Amount',
    'MolarConductivity':'Conductance / Amount',
    'Molality':'Amount / Mass',
    'MolarMass':'Mass / Amount',
    'CatalyticEfficiency':'MolarVolume / Time',

    # Electromagnetics
    'PolarizationDensity':'Charge / Area',
    'ChargeDensity':'Charge / Volume',
    'CurrentDensity':'Current / Area',
    'Conductivity':'Conductance / Length',
    'Permittivity':'Capacitance / Length',
    'MagneticPermeability':'Inductance / Length',
    'ElectricFieldStrength':'Force / Charge',
    'Magnetization':'Current / Distance',
    'MagneticFieldStrength':'Force / Current',
    'IonizingRadiationExposure':'Charge / Mass',
    'Resistivity':'Resistance Length',
    'LinearChargeDensity':'Charge / Length',
    'MagneticDipoleMoment':'Energy / MagneticFluxDensity',
    'ElectronMobility':'Area / MagneticFlux',
    'Reluctance':'Inductance^-1',
    'MagneticVectorPotential':'MagneticFluxDensity Distance',
    'MagneticMoment':'MagneticFlux Radius',
    'MagneticRigidity':'MagneticFluxDensity Distance',
    'MagnetoMotiveForce':'Current Angle',
    'MagneticSusceptibility':'Length / Inductance',

    # Thermodynamics
    'Entropy':'Energy / Tempurature',
    'SpecificEntropy':'Entropy / Mass',
    'HeatCapacity':'Heat / Tempurature',
    'SpecificHeatCapacity':'HeatCapacity / Mass',
    'ThermalConductance':'RadiantFlux / Tempurature',
    'ThermalConductivity':'ThermalConductance / Length',
    'ThermalResistance':'ThermalConductance^-1',
    'ThermalResistivity':'ThermalResistance / Length',
    'ThermalExpansion':'Tempurature^-1',
    'TempuratureGradient':'Tempurature / Length',

    # Information Technologies
    'Information':'Entropy',
    'BitRate':'Information / Time',
    'Signal':'Information',
    'BaudRate':'Signal / Time',
    'BaudDensity':'Information / Signal',
    'SignalErrorRate':'BaudDensity Activity',
}

systems = {
    'SI':{
        'units':{
            's':'Time',
            'm':'Distance',
            'kg':'Mass',
            'A':'Current',
            'K':'Tempurature',
            'mol':'Amount',
            'cd':'LuminousIntensity',
            'Hz':'Frequency',
            'r':'Angle',
            'sr':'SolidAngle',
            'N':'Force',
            'Pa':'Pressure',
            'J':'Energy',
            'W':'Power',
            'C':'Charge',
            'V':'Voltage',
            'F':'Capacitance',
            'Ω':'Resistance',
            'S':'Conductance',
            'Wb':'MagneticFlux',
            'T':'MagneticFluxDensity',
            'H':'Inductance',
            'lm':'LuminousFlux',
            'lx':'Illuminance',
            'Bq':'Activity',
            'Gy':'AbsorbedRadiationDose',
            'Sv':'EquivalentRadiationDose',
            'kat':'CatalyticActivity',
        },
        'usesPrefixes':True,
        'prefixSets':[
            {
                'exponent':10,
                'prefixes':{
                    'q': -30,
                    'r': -27,
                    'y': -24,
                    'z': -21,
                    'a': -18,
                    'f': -15,
                    'p': -12,
                    'n': -9,
                    'μ': -6,
                    'm': -3,
                    'c': -2,
                    'd': -1,
                    'da': 1,
                    'h' : 2,
                    'k' : 3,
                    'M' : 6,
                    'G' : 9,
                    'T' : 12,
                    'P' : 15,
                    'E' : 18,
                    'Z' : 21,
                    'Y' : 24,
                    'R' : 27,
                    'Q' : 30,
                }
            }
        ],
        'aliases':{
            'μ':['u'],
            'Ω':['Ohm'],
        }
    },
}

defaultSystem = 'SI'
