namedUnits = {
    "Hz":"s^-1",
    "r":"m / m",
    "sr":"m^2 / m^2",
    "N":"kg m / s^2",
    "Pa":"N / m^2",
    "J":"N m",
    "W":"J / s",
    "C":"A s",
    "V":"W / A",
    "F":"C / V",
    "Ω":"V / A",
    "S":"A / V",
    "Wb":"V s",
    "T":"Wb / m^2",
    "H":"Wb / A",
    "lm":"cd sr",
    "lx":"lm / m^2",
    "Bq":"s^-1",
    "Gy":"m^2 / s^2",
    "Sv":"m^2 / s^2",
    "kat":"mol / s",
}


# quantities = {
#     # Quantities with named units
#     'Frequency':'Time^-1',
#     'Angle':'Length / Radius',
#     'SolidAngle':'Area / Radius^2',
#     'Force':'Mass Acceleration',
#     'Pressure':'Force / Area',
#     'Energy':'Force / Length',
#     'Power':'Energy / Time',
#     'Charge':'Current Time',
#     'Voltage':'Power / Current',
#     'Capacitance':'Charge / Voltage',
#     'Resistance':'Voltage / Current',
#     'Impedance':'Voltage / Current',
#     'Reactance':'Voltage / Current',
#     'Conductance':'Current / Voltage',
#     'MagneticFlux':'Voltage Time',
#     'MagneticFluxDensity':'MagneticFlux / Area',
#     'Inductance':'MagneticFlux / Current',
#     'LuminousFlux':'LuminousIntensity / SolidAngle',
#     'Illuminance':'LuminousFlux / Area',
#     'Radioactivity':'Time^-1',
#     'AbsorbedRadiationDose':'Energy / Mass',
#     'EquivalentRadiationDose':'Energy / Mass',
#     'Entropy':'Energy / Tempurature',

#     # Kinematics
#     'Velocity':'Length / Time',
#     'Acceleration':'Velocity / Time',
#     'Jerk':'Acceleration / Time',
#     'Snap':'Jerk / Time',
#     'Yank':'Mass Jerk',
#     'AngularVelocity':'Angle / Time',
#     'AngularAcceleration':'AngularVelocity / Time',
#     'FrequencyDrift':'Frequency / Time',
#     'VolumetricFlow':'Volume / Time',

#     # Mechanics
#     'Area':'Length^2',
#     'Volume':'Length Area',
#     'Momentum':'Force Time',
#     'AngularMomentum':'Momentum Radius',
#     'Torque':'Force Radius',
#     'Wavenumber':'Length^-1',
#     'OpticalPower':'Length^-1',
#     'Curvature':'Radius^-1',
#     'SpatialFrequency':'Length^-1',
#     'AreaDensity':'Mass / Area',
#     'Density':'Mass / Volume',
#     'SpecificVolume':'Volume / Mass',
#     'Action':'Energy Time',
#     'SpecificEnergy':'Energy / Mass',
#     'EnergyDensity':'Energy / Volume',
#     'SurfaceTension':'Force / Length',
#     'Stiffness':'Energy / Area',
#     'Irradiance':'Power / Area',
#     'KinematicViscosity':'Area / Time',
#     'Diffusivity':'Area / Time',
#     'DynamicViscosity':'Pressure Time',
#     'LinearMassDensity':'Mass / Length',
#     'MassFlowRate':'Mass / Time',
#     'Radiance':'Power / SolidAngle Area',
#     'SpectralPower':'Power / Length',
#     'AbsorbedDoseRate':'AbsorbedDose / Time',
#     'FuelEfficiency':'Length / Volume',
#     'SpectralIrradiance':'Power / Volume',
#     'PowerDensity':'Power / Volume',
#     'EnergyFluxDensity':'Energy / Area Time',
#     'Compressibility':'Pressure^-1',
#     'RadiantExposure':'Energy / Area',
#     'InertialMoment':'Mass Radius^2',
#     'SpecificAngularMomentum':'AngularMoment / Mass',
#     'RadiantIntensity':'Power / SolidAngle',
#     'SpectralIntensity':'RadiantIntensity / Length',

#     # Chemistry
#     'Molarity':'Amount / Volume',
#     'MolarVolume':'Volume / Amount',
#     'MolarHeatCapacity':'Entropy / Amount',
#     'MolarEnergy':'Energy / Amount',
#     'MolarConductivity':'Conductivity Length / Amount',
#     'Molality':'Amount / Mass',
#     'MolarMass':'Mass / Amount',
#     'CatalyticEfficiency':'MolarVolume / Time',

#     # Electromagnetics
#     'PolarizationDensity':'Charge / Area',
#     'ChargeDensity':'Charge / Volume',
#     'CurrentDensity':'Current / Area',
#     'Conductivity':'Conductance / Length',
#     'Permittivity':'Capacitance / Length',
#     'MagneticPermeability':'Inductance / Length',
#     'ElectricFieldStrength':'Voltage / Length',
#     'Magnetization':'Current / Length',
#     'Exposure':'Charge / Mass',
#     'Resistivity':'Resistance Length',
#     'LinearChargeDensity':'Charge / Length',
#     'MagneticDipoleMoment':'Energy / MagneticFluxDensity',
#     'ElectronMobility':'Area / MagneticFlux',
#     'Reluctance':'Inductance^-1',
#     'MagneticVectorPotential':'MagneticFlux / Length',
#     'MagneticMoment':'MagneticFlux Length',
#     'MagneticRigidity':'MagneticFluxDensity Length',
#     'MagnetomotiveForce':'Current Angle',
#     'MagneticSusceptibility':'Length / Inductance',

#     # Photometry
#     'LuminousEnergy':'LuminousFlux Time',
#     'LuminousExposure':'Illuminance Time',
#     'Luminance':'LuminousIntensity / Area',
#     'LuminousEfficacy':'LuminousFlux / Power',

#     # Thermodynamics
#     'HeatCapacity':'Energy / Tempurature',
#     'SpecificHeatCapacity':'HeatCapacity / Mass',
#     'ThermalConductance':'Power / Tempurature',
#     'ThermalConductivity':'ThermalConductance / Length',
#     'ThermalResistance':'Tempurature / Power',
#     'ThermalResistivity':'ThermalResistance / Length',
#     'ThermalExpansion':'Tempurature^-1',
#     'TempuratureGradiant':'Tempurature / Length',
# }

# print(len(quantities))

baseQuantities = {
    'Time':'s',
    'Distance':'m',
    'Mass':'kg',
    'Current':'A',
    'Tempurature':'K',
    'Amount':'mol',
    'LuminousIntensity':'cd',
}

quantities = {
    # Disambiguations
    'Length':'Distance',
    'Radius':'Distance',
    'Heat':'Energy',
    'Dose':'Mass',

    #Quantities with named units
    'Frequency':'Time^-1',
    'Angle':'Length / Radius',
    'SolidAngle':'Area / Radius^2',
    'Force':'Mass Acceleration',
    'Pressure':'Force / Area',
    'Energy':'Force Distance',
    'Power':'Energy / Time',
    'Charge':'Current Time',
    'Voltage':'Power / Current',
    'Capacitance':'Charge / Voltage',
    'Resistance':'Voltage / Current',
    'Reactance':'Voltage / Current',
    'Impedance':'Voltage / Current',
    'Conductance':'Current / Voltage',
    'MagneticFlux':'Voltage Time',
    'MagneticFluxDensity':'MagneticFlux / Area',
    'Inductance':'MagneticFlux / Current',
    'LuminousFlux':'LuminousIntensity / SolidAngle',
    'Illuminance':'LuminousFlux / Area',
    'Activity':'Time^-1',
    'AbsorbedRadiationDose':'Energy / Mass',
    'EquivalentRadiationDose':'Energy / Mass',

    # Kinematics
    'Velocity':'Distance / Time',
    'Acceleration':'Velocity / Time',
    'Jerk':'Acceleration / Time',
    'Snap':'Jerk / Time',
    'Yank':'Mass Jerk',
    'AngularVelocity':'Angle / Time',
    'AngularAcceleration':'AngularVelocity / Time',
    'FrequencyDrift':'Frequency / Time',
    'VolumetricFlow':'Volume / Time',

    # Mechanics
    'Area':'Length^2',
    'Volume':'Length Area',
    'Momentum':'Force Time',
    'AngularMomentum':'Momentum Radius',
    'Torque':'Force Radius',
    'SpatialFrequency':'Length^-1',
    'OpticalPower':'Distance^-1',
    'Curvature':'Radius^-1',
    'AreaDensity':'Mass / Area',
    'Density':'Mass / Volume',
    'SpecificVolume':'Volume / Mass',
    'Action':'Energy Time',
    'SpecificEnergy':'Energy / Mass',
    'EnergyDensity':'Energy / Volume',
    'SurfaceTension':'Force / Distance',
    'Stiffness':'Energy / Area',
    'Diffusivity':'Area / Time',
    'KinematicViscosity':'DynamicViscosity / Density',
    'DynamicViscosity':'Pressure Time',
    'LinearMassDensity':'Mass / Length',
    'MassFlowRate':'Mass / Time',
    'AbsorbedRadiationDoseRate':'AbsorbedRadiationDose / Time',
    'FuelEfficiency':'Distance / Volume',
    'PowerDensity':'Power / Volume',
    'EnergyFluxDensity':'Power / Area',
    'Compressibility':'Pressure^-1',
    'InertialMoment':'Mass Radius^2',
    'SpecificAngularMomentum':'AngularMomentum / Mass',
    
    # Radiometry
    'RadiantFlux':'Heat / Time',
    'SpectralPower':'RadiantFlux / Length',
    'SpectralFlux':'RadiantFlux / Length',
    'RadiantIntensity':'RadiantFlux / SolidAngle',
    'SpectralIntensity':'RadiantIntensity / Length',
    'Radiance':'RadiantIntensity / Area',
    'SpectralRadiance':'Radiance / Length',
    'Irradiance':'RadiantFlux / Area',
    'SpectralIrradiance':'Irradiance / Length',
    'Radiosity':'RadiantFlux / Area',
    'SpectralRadiosity':'Radiosity / Length',
    'RadiantExitance':'RadiantFlux / Area',
    'SpectralExitance':'RadiantExitance / Length',
    'RadiantExposure':'Irradiance Time',
    'SpectralExposure':'RadiantExposure / Length',

    # Photometry
    'LuminousEnergy':'LuminousFlux Time',
    'Luminance':'LuminousIntensity / Area',
    'LuminousExitance':'LuminousFlux / Area',
    'LuminousExposure':'LuminousExitance Time',
    'LuminousEnergyDensity':'LuminousEnergy / Volume',
    'RadiationEfficacy':'LuminousFlux / RadiantFlux',
    'LuminousEfficacy':'LuminousFlux / Power',

    # Chemistry
    'Molarity':'Amount / Volume',
    'MolarVolume':'Volume / Amount',
    'MolarHeatCapacity':'HeatCapacity / Amount',
    'MolarEnergy':'Energy / Amount',
    'MolarConductivity':'Conductance / Amount',
    'Molality':'Amount / Mass',
    'MolarMass':'Mass / Amount',
    'CatalyticEfficiency':'MolarVolume / Time',

    # Electromagnetics
    'PolarizationDensity':'Charge / Area',
    'ChargeDensity':'Charge / Volume',
    'CurrentDensity':'Current / Area',
    'Conductivity':'Conductance / Length',
    'Permittivity':'Capacitance / Length',
    'MagneticPermeability':'Inductance / Length',
    'ElectricFieldStrength':'Force / Charge',
    'Magnetization':'Current / Distance',
    'MagneticFieldStrength':'Force / Current',
    'IonizingRadiationExposure':'Charge / Mass',
    'Resistivity':'Resistance Length',
    'LinearChargeDensity':'Charge / Length',
    'MagneticDipoleMoment':'Energy / MagneticFluxDensity',
    'ElectronMobility':'Area / MagneticFlux',
    'Reluctance':'Inductance^-1',
    'MagneticVectorPotential':'MagneticFluxDensity Distance',
    'MagneticMoment':'MagneticFlux Radius',
    'MagneticRigidity':'MagneticFluxDensity Distance',
    'MagnetoMotiveForce':'Current Angle',
    'MagneticSusceptibility':'Length / Inductance',

    # Thermodynamics
    'Entropy':'Energy / Tempurature',
    'SpecificEntropy':'Entropy / Mass',
    'HeatCapacity':'Heat / Tempurature',
    'SpecificHeatCapacity':'HeatCapacity / Mass',
    'ThermalConductance':'RadiantFlux / Tempurature',
    'ThermalConductivity':'ThermalConductance / Length',
    'ThermalResistance':'ThermalConductance^-1',
    'ThermalResistivity':'ThermalResistance / Length',
    'ThermalExpansion':'Tempurature^-1',
    'TempuratureGradient':'Tempurature / Length',

    # Pharmacology
    'Dosage':'Dose / Mass',
    'Concentration':'Dose / Volume',

    # Information Technologies
    'Information':'Entropy',
    'BitRate':'Information / Time',
    'Signal':'Information',
    'BaudRate':'Signal / Time',
    'BaudDensity':'Information / Signal',
    'SignalErrorRate':'BaudDensity Activity',
    'BlockIntegrity':''
}

if __name__ == '__main__':
    print(len(quantities) + len(baseQuantities))